#!/usr/bin/env python3
"""
Module that lists all databases in MongoDB.
"""

from pymongo import MongoClient


def list_databases():
    """
    Connect to MongoDB and print the list of databases.
    """
    client = MongoClient('mongodb://localhost:27017/')
    databases = client.list_database_names()
    for db in databases:
        print(db)


if __name__ == "__main__":
    list_databases()
